# Generated by Django 5.2.8 on 2025-12-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0002_category_store_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリ一覧'},
        ),
        migrations.AddField(
            model_name='category',
            name='keyword',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='キーワード'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='カテゴリ名'),
        ),
    ]
