# Generated by Django 5.2.8 on 2025-12-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0003_alter_category_options_category_keyword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='食べ物名')),
            ],
        ),
    ]
