# Generated by Django 5.2.8 on 2025-12-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0004_food_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food_category',
            options={'verbose_name': '食べ物', 'verbose_name_plural': '食べ物一覧'},
        ),
        migrations.AddField(
            model_name='store',
            name='food_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelog.food_category'),
        ),
    ]
