# Generated by Django 5.2.8 on 2025-12-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0005_alter_food_category_options_store_food_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_category',
            new_name='FoodCategory',
        ),
    ]
