# Generated by Django 5.2.8 on 2025-12-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0006_rename_food_category_foodcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='food_category',
        ),
        migrations.AddField(
            model_name='store',
            name='food_categories',
            field=models.ManyToManyField(blank=True, related_name='stores', to='tabelog.foodcategory'),
        ),
    ]
